### ISSUE TITLE
Custom functions to determine whether or not to pin/unpin headroom element

### ISSUE THREAD

**Issue by jeffshaver** [WickyNilliams/headroom.js#96] opened 2014-07-09 00:51 UTC
In a modified version of this that I changed, I added the ability to pass in two new options: shouldPinCheck and shouldUnpinCheck (couldn't think of better names). These are functions that must return true/false. They are fired inside the shouldPin/shouldUnpin functions in the return statement.

Therefore, if a headroom goes to unpin and the shouldUnpinCheck returns false, the headroom element shouldn't be unpinned. Same thing for the shouldPinCheck but opposite.

If it was useful to me, I thought it may be useful to someone else as well. Maybe this should be added into the codebase.

**Comment by WickyNilliams** [comment] 2015-01-12 19:08
Closing as this is effectively a duplicate of #38 and the PR #125 offers a potential solution

**Closed by WickyNilliams** 2015-01-12 19:08 UTC
