### ISSUE TITLE
Chrome 49 smooth scrolling glitch

### ISSUE THREAD

**Issue by Slamik** [WickyNilliams/headroom.js#205] opened 2016-03-27 12:42 UTC
Good day,

In some cases, header opens (or hides) twice on scrolling up or scrolling down.
When smooth scrolling is disabled - everything is ok.

**Comment by WickyNilliams** [comment] 2016-04-13 16:42
What is "smooth scrolling"? Which OS? Do you detailed steps to reproduce?

**Comment by Slamik** [comment] 2016-04-15 19:59
Sorry for imprecision.

OS: Windows 10, Chrome 49 (there were two builds deployed).
When I am scrolling down or scrolling up, in some cases, header opens twice per sec.
chrome://flags/#enable-smooth-scrolling (turned on by default in 49 build). When this option is disabled - everything is ok.
In the new version of Chrome (50), the issue apparently resolved.

**Comment by WickyNilliams** [comment] 2016-06-02 14:24
Hmm I guess that this was a brief chrome bug (possibly related to scroll events). Since you say it has been fixed in v50, I will close this

**Closed by WickyNilliams** 2016-06-02 14:24 UTC
