### ISSUE TITLE
Documentation on header.js site out of date with github docs.

### ISSUE THREAD

**Issue by HoldenCreative** [WickyNilliams/headroom.js#153] opened 2015-03-09 14:44 UTC
Thanks for header.js!  Lovely solution.

I was attempting to get header.js working with my Angular instance and wasn't having much luck until I noticed that there was a config available to target a "scrollable area" in the github readme (scroller=".app-view").  The web site documentation doesn't mention this option.

**Comment by auginator** [comment] 2015-03-12 15:08
+1 - the configurable scrollable area is fantastic. 
The default options object here on Github page should be this one:

    /**
        * Default options
        * @type {Object}
    */
    Headroom.options = {
        tolerance : {
            up : 0,
            down : 0
        },
        offset : 0,
        scroller: window,
        classes : {
            pinned : 'headroom--pinned',
            unpinned : 'headroom--unpinned',
            top : 'headroom--top',
            notTop : 'headroom--not-top',
            initial : 'headroom'
        }
    };

**Comment by WickyNilliams** [comment] 2015-04-08 15:37
Duplicate of #78. Will get this fixed. Sorting through open issues first, then prioritising

**Closed by WickyNilliams** 2015-04-08 15:37 UTC
