### ISSUE TITLE
Add bottom offset option

### ISSUE THREAD

**Issue by scsskid** [WickyNilliams/headroom.js#321] opened 2019-07-08 13:35 UTC
Really great script, totally loving it

Could you please off an bottom offset option, so its able to pin an "scroll to top" link only when suer is at an certain offset from bottom, I already pin it only when scrolling up, but the bottom offset would add more fine tuning possibilities

I'm trying to get .headroom-not-bottom to trigger only from a certain bottom offset, to avoid the ealry repositioning

![headroom](https://user-images.githubusercontent.com/365724/60814837-ad874300-a196-11e9-9c5f-9df65c5d9a3e.gif)

**Comment by WickyNilliams** [comment] 2019-08-12 16:19
I think this is a duplicate of #303. There is an outstanding PR for this, which i hope to get merged soon. If I am mistaken, please let me know

**Closed by WickyNilliams** 2019-08-12 16:19 UTC

**Comment by scsskid** [comment] 2019-08-12 21:52
great, thanks for reply
and congratulations to make even sense of my sloppy sentences lol

**Comment by WickyNilliams** [comment] 2019-08-22 17:15
Ah, I don't think this is actually a duplicate of #303. #303 seems to want a different offset depending on direction of scroll. Whereas this wants an offset at the bottom of the page, right?
