### ISSUE TITLE
This library is not actively maintained. Is there an alternative to Headroom?

### ISSUE THREAD

**Issue by liquidvisual** [WickyNilliams/headroom.js#312] opened 2019-02-24 23:54 UTC
It's such a vital library for websites, but I think we should all be using something that is more actively maintained. Does anyone use/know of any alternatives?

**Comment by nikkijd** [comment] 2019-02-25 05:45
up

**Comment by WickyNilliams** [comment] 2019-02-26 09:27
Closing, as this is not an issue/bug/feature request

**Closed** 2019-02-26 09:27 UTC

**Comment by lkraav** [comment] 2019-05-26 10:14
Duplicate of https://github.com/WickyNilliams/headroom.js/issues/311

**Comment by rokumatsumoto** [comment] 2019-09-05 23:43
The same old headroom simplified
https://yarnpkg.com/en/package/headroom
