### ISSUE TITLE
Menu bump on mobile

### ISSUE THREAD

**Issue by LIJE** [WickyNilliams/headroom.js#355] opened 2019-12-11 22:35 UTC
Hi,

I noticed on mobile when you scroll to the top, you get some kind of "hide then show" bump effect.
You can see the effect here: https://dev.mediagora.co/
I'm using Android on a OnePlus 5T with Chrome.

**Comment by LIJE** [comment] 2019-12-16 15:40
Are you still working on it?

**Comment by WickyNilliams** [comment] 2020-01-09 15:23
@LIJE sorry for the delay in response. I'm not sure what the issue was, as the site seems to now have an "in development" placeholder on it. Is it OK to close this now?

**Comment by LIJE** [comment] 2020-01-13 07:53
Website is enabled again. I was working on it. You can check this out now.

**Comment by LIJE** [comment] 2020-01-15 22:36
Hi there,

Did you get a change to test it?

**Comment by WickyNilliams** [comment] 2020-01-16 16:18
I just had a quick look. It's hard to diagnose because there's other stuff going, but at a guess I'd say it's something to do with the `.x-bar-absolute` class, which uses `position: absolute`. The header element should be `position: fixed`. 

In any case, I'm sure this is a problem with your implementation and not a bug. So I'm going to close this issue.

**Closed by WickyNilliams** 2020-01-16 16:18 UTC
