### ISSUE TITLE
Scroll down, up and down again uses pinned instead of unpinned

### ISSUE THREAD

**Issue by slacto** [WickyNilliams/headroom.js#233] opened 2016-06-14 07:19 UTC
I included the script like ths:

```
    $('.js-header').headroom({
        'offset': 150,
        'tolerance': 5,
        'classes': {
            'initial': 'animated',
            'pinned': 'slideDown',
            'unpinned': 'slideUp'
        }
    });
```

Scroll down
headroom--top headroom--not-bottom
headroom--not-bottom headroom--not-top slideUp

Scroll up
headroom--not-bottom headroom--not-top slideDown
headroom--not-bottom slideDown headroom--top

Scroll down again
headroom--not-bottom **slideDown** headroom--top
headroom--not-bottom headroom--not-top slideUp

I don't understand why 'slideDown' is set when I scroll down again. It makes this state hard to style.
As I see it classes should be the same whenever I scroll down.

**Comment by slacto** [comment] 2016-07-07 12:51
How do I avoid the 'pinned' class second time I scroll down / slide up? It should only be 'pinned' when I scroll up / slide down, right?

**Comment by WickyNilliams** [comment] 2017-03-21 15:14
I was not able to reproduce this. I'm closing this in the interest of cleaning up the issue tracker. If you are still having problems, or can provide a reduced test case, please comment here

**Closed by WickyNilliams** 2017-03-21 15:14 UTC
